### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by javiervargas** [BlockchainCommons/spotbit#16]
Hi,

Intermittently spotbit shows this message when I try to get history data.   Server is running well most of the time,  but suddenly it appears to block database.   Few minutes ago it returns data.

```
127.0.0.1 - - [25/Aug/2020 15:50:39] "GET /hist/USD/coinbase/1597348471/1599354186 HTTP/1.1" 500 -
[2020-08-25 15:50:58.774689] | inserted into kraken USD 518400 times
[2020-08-25 15:51:56.993359] | inserted into kraken GBP 331776 times
[2020-08-25 15:52:33,295] ERROR in app: Exception on /hist/USD/coinbase/1597348471/1599354186 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 187, in hist
    cursor = db_n.execute(statement)
sqlite3.OperationalError: database is locked
127.0.0.1 - - [25/Aug/2020 15:52:33] "GET /hist/USD/coinbase/1597348471/1599354186 HTTP/1.1" 500 -
[2020-08-25 15:52:54.923558] | inserted into kraken JPY 312481 times
[2020-08-25 15:53:05.641895] | inserted into bitfinex USD 3600 times
[2020-08-25 15:53:14.362819] | inserted into bitfinex GBP 1296 times
```
Further i'm wonder if there're plans to support https?
Tor is not working for me on proxy reversal scenarios.

Regards.
J.

**Comment by watersnake1** [comment]
Right now I am not able to access my home network or computer so I cannot set that up right now but can next week. Sorry for the delay on that. As for the database locked error, make sure spotbit is running as root. That may be why it can't open the database. I will also look into that when I can.

**Comment by nochiel** [comment]
Spotbit no longer uses a local database. Historical data is retrieved directly from configured exchanges.
